// Auto-generated by scripts/generate-db-config.js
// prettier-ignore
module.exports = { databaseUrl: "postgresql://neondb_owner:npg_GYnSRj3lZcV5@ep-old-star-abhpdbpp-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require" };
