[build]
  command = "npm run build"
  publish = "dist/devsnips/browser"
  functions = "netlify/functions"

[build.environment]
  NEON_API_KEY = "napi_wbe9606viy6fjzjti2k2fe5dhplh4ug1swa86615tuc3mpahx9hooyrr9vjb4ww3"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
